### PR TITLE
Add load balancer + retry logic

### PR DESCRIPTION
**Pull request by dmahmalat**
Closed and re-opened to clean up commit history and make a review easier.

In the UI, with this PR you can add multiple tunnels to the same domain name.
They still need different client names tho - then the server will pick one from the list and route traffic to one of the clients.

For example, say you have 3 instances of the same website running for redundancy.
On each website host (or daemonset pod in k8s), you'd run the boringproxy client with a unique client name (ex website-1, website-2, website-3).
On the UI, you'd have 3 different entries for [www.example.com](http://www.example.com/) (each pointing to the different clients where the boringproxy clients are running ex. website-1, website-2, website-3)
When you go to [www.example.com](http://www.example.com/), the boringproxy server would select one client in the list and route traffic there, and would retry to a different client if the connection were to fail.

### CODE REVIEW

**Comment by anderspitman** [comment]
Hey @dmahmalat just wanted to give you an update. I've thought more about this and I really don't think I'll be adding load balancing in the near future. It seems to me that if your system needs a load balancer, boringproxy probably isn't the right tool for your job. For one thing it's not stable enough yet (pre 1.0). Also it uses rather inefficient SSH tunneling under the hood, so you're doing things like double encryption and have to deal with TCP head-of-line blocking. Overall boringproxy is targeted at self-hosters who want to do things like manage their own cloud storage or host a Jellyfin server for their family.

Also, I'm in the process of implementing an entirely different way of creating tunnels based on OAuth2. There's a good chance it will have an impact on features like load balancing, so I don't want to commit to a load balancing implementation yet.

Now, that said, I'd encourage you to keep this PR open if you want to. This branch may well be useful to others. But it could be annoying for you to keep up with merging upstream changes.

Also, I'm very open to hearing from you or others arguments in favor of adding load balancing to boringproxy. If there are compelling use cases for the average self-hoster I'd like to hear about them.

**Comment by dmahmalat** [comment]
No problem at all !

I'll keep this open for now since I use it for my own purposes (and in case it can be useful to others in the meantime).
It doesn't have the best implementation anyway (load balancing is more or less random between clients and I might implement a health check to avoid routing to offline clients).

My own use case is I self host a k8s cluster at home and would like to route traffic from the internet to the cluster (without opening ports/firewall etc. on the local machine). I'm trying to keep things as HA as possible, hence the load balancer in case the node which hosts the boringproxy client goes offline.

There are probably better ways to do this, so I'm experimenting with different solutions. What I like about boringproxy is that it sets up the SSH keys and tunnels neatly for me, so I don't have to do any extra configurations. I could potentially even automate creating/deleting tunnels via the API when a new node is created or deleted which would be really neat !

**Comment by anderspitman** [comment]
Sounds good, thanks again for the contribution. Just to make sure, you're aware of the list here right?

https://github.com/anderspitman/awesome-tunneling

In particular maybe take a look at Teleport. If you don't need an open source option I know inlets integrates closely with k8s. Check Kubesail as well.

**Comment by dmahmalat** [comment]
Thanks I'll definitely check out Teleport 
I'm looking for something opensource - inlets looked very promising but I didn't like that it didn't provide full control over the source so I ended up finding this repo !

**Comment by anderspitman** [comment]
Yeah the sad part is Inlets started out open source. But as I understand it the founder wasn't able to make money in a sustainable way so closed the source to try a different approach. Hope it works out for him.

**Pull request closed without merging**
