### PR TITLE
Add load balancer

### PR DESCRIPTION
**Pull request by dmahmalat**
This adds a very basic load balancer.

Tunnels are no longer mapped by domain name, but by domain name and client.
Once a domain is requested, the code checks to see if other clients reference the same domain and picks one tunnel from the list.

### CODE REVIEW

**Comment by lrvl** [comment]
Looks useful, could example documentation on how to load balance be added?

**Comment by anderspitman** [comment]
Hey @dmahmalat, thanks for the PR! I don't know when I'll get a chance to look at it, but I'll leave this open for now.

**Comment by dmahmalat** [comment]
> Looks useful, could example documentation on how to load balance be added?

In the UI, with this PR you can add multiple tunnels to the same domain name.
They still need different client names tho - then the server will pick one from the list and route traffic to one of the clients.

For example, say you have 3 instances of the same website running for redundancy.
On each website host (or daemonset pod in k8s), you'd run the boringproxy client with a unique client name (ex website-1, website-2, website-3).
On the UI, you'd have 3 different entries for www.example.com (each pointing to the different clients where the boringproxy clients are running ex. website-1, website-2, website-3)
When you go to www.example.com, the boringproxy server would select one client in the list and route traffic there.

**Comment by dmahmalat** [comment]
Cleaned this up - this PR now only contains the load balancer + retry logic.

**Comment by dmahmalat** [comment]
Closing - re-opening with cleaned up commit history.

**Pull request closed without merging**
