### PR TITLE
Systemd Integration and Docs

### PR DESCRIPTION
**Pull request by voidrot**
Thanks for the awesome project. Since it has made my life so much easier on self-hosting some services I wanted to contribute back some of the stuff that I had setup to make it easier.

This PR adds a systemd service file for the server & and a template service file for clients.

I have also written up how to use it all in the systemd-integration.md file.

Just let me know if there is anything missing or any changes you would like.

### CODE REVIEW

**Comment by anderspitman** [comment]
Hi @voidrot. Thanks for the contribution; systemd integration is very useful. I'd be happy to merge this after a few modifications:

1. The official name is boringproxy, not BoringProxy. Please rename it in the new docs.
2. Create a docs directory and move the new md file into there. I've already been bloating the root directory too much...
3. Create a systemd directory and move the unit files into there. The scripts directory is mostly for runnable tools.
4. I really prefer not to encourage people to run commands as root, including curl and wget. I know you mention it at the bottom, but can you re-arrange things so root isn't used for anything except what is required, ie creating the systemd files and enabling the services?

Thanks again, and let me know if you have any questions.

**Comment by voidrot** [comment]
@anderspitman Updated as requested. I apologize for the project name, bad habits with my keyboard. 

The systemd unit files have been updated to run as the `boringproxy` user and group as the default and moved into the `systemd` directory.

The commands in the docs have sudo prefixed as an assumption that the user will be running the commands from a standard user account that has sudo access. other than the setup commands nothing else requires root/sudo privileges.

I also moved the systemd doc into the `docs` directory and also reworked it a bit to try and make it easier to understand.

**Comment by anderspitman** [comment]
Looks much better, thanks. Only thing I would still request changed is the sudo curl and sudo wget. curl and wget are both fairly complex programs that could have security bugs. Would you mind splitting it into separate commands so you download to a temporary location without sudo and then sudo cp the files to the final location?

**Comment by arp242** [comment]
One option might be to put the service files in the binary itself, just as a `const systemdUnit = `[...]`, and then print that with `boringproxy systemd` and/or `boringproxy systemd > path/to/whatever`.

Then you don't need to fetch anything from the network with anything, and just the `boringproxy` binary is enough.

You could even add some options to automate steps like:

> Edit `/etc/systemd/system/boringproxy-client@.service` and replace the server address `bp.example.com` with the domain that the server is located at. EX: `-server proxy.bpuser.me`:

    $ boringproxy systemd -server proxy.bpuser.me

Will print the unit file with the correct address printf'd in.

**Comment by arp242** [comment]
Actually, I see now it already uses go-rice to embed the template files, so could use that as well if you want to go down this route. Go 1.16 will make this easier with `go:embed` as well.

**Comment by anderspitman** [comment]
@arp242 I like the idea, but would prefer to keep the systemd stuff in the docs for now. Docs can be removed at any time, but built-in commands become part of the public API that must be maintained.

This does make me think though. @voidrot rather than having separate files for the systemd units, what do you think about just putting the examples in the markdown docs and telling them to copy/paste it?

**Comment by arp242** [comment]
Yeah, fair enough; just a suggestion :-)

**Comment by voidrot** [comment]
@anderspitman yeah I can update the commands, also would you want me to throw it all into a bash script that is run as such `wget https://<raw github link> | bash`

**Comment by anderspitman** [comment]
@voidrot nah I think it's fine as-is. Thanks again!

**Pull request merged**
