### PR TITLE
accept-ca-terms

### PR DESCRIPTION
**Pull request by WGrobler**
Changes:

- removed "RUN export VERSION='2'" from Dockerfile, this was accidentally left over from previous testing
- added a WORKDIR for image
- added acceptCATerms to automatically accept terms when starting docker container
- updated README to reflect changes
- updated docker-compose to reflect changes

### CODE REVIEW

**Comment by anderspitman** [comment]
:+1:

**Comment by anderspitman** [comment]
Oh @WGrobler one other thing. Not a big deal but if you can run `go fmt ./...` before you commit it helps keep the code tidier. Thanks!

**Comment by WGrobler** [comment]
> Oh @WGrobler one other thing. Not a big deal but if you can run go fmt ./... before you commit it helps keep the code tidier.

Didn't know Go could do it. 
It's nice to start learning Go, will surely do so in the future.

**Comment by anderspitman** [comment]
I've gotten pretty hooked on Go. Coming from C/Python/JavaScript I wanted to start using Rust for more things, but I'm just not productive enough. I can move so much faster in Go. It just makes some really good tradeoff decisions.

**Pull request merged**
